export const ACTION_TYPE = {
	SET_TODOS: 'SET_TODOS',

	SET_IS_LOADING_START: 'SET_IS_LOADING_START',
	SET_IS_LOADING_STOP: 'SET_IS_LOADING_STOP',

	SET_REFRESH_TODOS: 'SET_REFRESH_TODOS',

	SET_VALUE: 'SET_VALUE',
	RESET_VALUE: 'RESET_VALUE',

	SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
	RESET_SEARCH_VALUE: 'RESET_SEARCH_VALUE',

	SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
	RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',

	SET_ON_SORT: 'SET_ON_SORT',

	SET_EDIT_ID: 'SET_EDIT_ID',
	RESET_EDIT_ID: 'RESET_EDIT_ID',
};
